void gemm_dense_snb(const double* A, const double* B, double* C) {
  __asm__ __volatile__("movq %0, %%rdi\n\t"
                       "movq %1, %%rsi\n\t"
                       "movq %2, %%rdx\n\t"
                       "movq $0, %%r12\n\t"
                       "movq $0, %%r13\n\t"
                       "movq $0, %%r14\n\t"
                       "0:\n\t"
                       "addq $3, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $12, %%r12\n\t"
                       "vmovapd 0(%%rdx), %%ymm7\n\t"
                       "vmovapd 32(%%rdx), %%ymm8\n\t"
                       "vmovapd 64(%%rdx), %%ymm9\n\t"
                       "vmovapd 384(%%rdx), %%ymm10\n\t"
                       "vmovapd 416(%%rdx), %%ymm11\n\t"
                       "vmovapd 448(%%rdx), %%ymm12\n\t"
                       "vmovapd 768(%%rdx), %%ymm13\n\t"
                       "vmovapd 800(%%rdx), %%ymm14\n\t"
                       "vmovapd 832(%%rdx), %%ymm15\n\t"
                       "vbroadcastsd 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 72(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 144(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vbroadcastsd 8(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 80(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 152(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vbroadcastsd 16(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 88(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 160(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vbroadcastsd 24(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 96(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 168(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vbroadcastsd 32(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 104(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 176(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vbroadcastsd 40(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 112(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 184(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vbroadcastsd 48(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 120(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 192(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vbroadcastsd 56(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 128(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 200(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vbroadcastsd 64(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 136(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 208(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm7, %%ymm7\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm10, %%ymm10\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm4\n\t"
                       "vaddpd %%ymm4, %%ymm13, %%ymm13\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm8, %%ymm8\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm11, %%ymm11\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm5\n\t"
                       "vaddpd %%ymm5, %%ymm14, %%ymm14\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vmulpd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm9, %%ymm9\n\t"
                       "vmulpd %%ymm3, %%ymm1, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm12, %%ymm12\n\t"
                       "vmulpd %%ymm3, %%ymm2, %%ymm6\n\t"
                       "vaddpd %%ymm6, %%ymm15, %%ymm15\n\t"
                       "vmovapd %%ymm7, 0(%%rdx)\n\t"
                       "vmovapd %%ymm8, 32(%%rdx)\n\t"
                       "vmovapd %%ymm9, 64(%%rdx)\n\t"
                       "vmovapd %%ymm10, 384(%%rdx)\n\t"
                       "vmovapd %%ymm11, 416(%%rdx)\n\t"
                       "vmovapd %%ymm12, 448(%%rdx)\n\t"
                       "vmovapd %%ymm13, 768(%%rdx)\n\t"
                       "vmovapd %%ymm14, 800(%%rdx)\n\t"
                       "vmovapd %%ymm15, 832(%%rdx)\n\t"
                       "addq $96, %%rdx\n\t"
                       "subq $3360, %%rdi\n\t"
                       "cmpq $48, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $768, %%rdx\n\t"
                       "addq $216, %%rsi\n\t"
                       "subq $384, %%rdi\n\t"
                       "cmpq $9, %%r13\n\t"
                       "jl 0b\n\t"
                       : : "m"(A), "m"(B), "m"(C) : "rdi","rsi","rdx","r12","r13","r14","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15");
}

#ifdef __AVX2__

void gemm_dense_hsw(const double* A, const double* B, double* C) {
  __asm__ __volatile__("movq %0, %%rdi\n\t"
                       "movq %1, %%rsi\n\t"
                       "movq %2, %%rdx\n\t"
                       "movq $0, %%r12\n\t"
                       "movq $0, %%r13\n\t"
                       "movq $0, %%r14\n\t"
                       "0:\n\t"
                       "addq $3, %%r13\n\t"
                       "movq $0, %%r12\n\t"
                       "1:\n\t"
                       "addq $16, %%r12\n\t"
                       "vmovapd 0(%%rdx), %%ymm4\n\t"
                       "vmovapd 32(%%rdx), %%ymm5\n\t"
                       "vmovapd 64(%%rdx), %%ymm6\n\t"
                       "vmovapd 96(%%rdx), %%ymm7\n\t"
                       "vmovapd 384(%%rdx), %%ymm8\n\t"
                       "vmovapd 416(%%rdx), %%ymm9\n\t"
                       "vmovapd 448(%%rdx), %%ymm10\n\t"
                       "vmovapd 480(%%rdx), %%ymm11\n\t"
                       "vmovapd 768(%%rdx), %%ymm12\n\t"
                       "vmovapd 800(%%rdx), %%ymm13\n\t"
                       "vmovapd 832(%%rdx), %%ymm14\n\t"
                       "vmovapd 864(%%rdx), %%ymm15\n\t"
                       "vbroadcastsd 0(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 72(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 144(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastsd 8(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 80(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 152(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastsd 16(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 88(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 160(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastsd 24(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 96(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 168(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastsd 32(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 104(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 176(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastsd 40(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 112(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 184(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastsd 48(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 120(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 192(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastsd 56(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 128(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 200(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vbroadcastsd 64(%%rsi), %%ymm0\n\t"
                       "vbroadcastsd 136(%%rsi), %%ymm1\n\t"
                       "vbroadcastsd 208(%%rsi), %%ymm2\n\t"
                       "vmovapd 0(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm4\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm8\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm12\n\t"
                       "vmovapd 32(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm5\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm9\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm13\n\t"
                       "vmovapd 64(%%rdi), %%ymm3\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm6\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm10\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm14\n\t"
                       "vmovapd 96(%%rdi), %%ymm3\n\t"
                       "addq $384, %%rdi\n\t"
                       "vfmadd231pd %%ymm3, %%ymm0, %%ymm7\n\t"
                       "vfmadd231pd %%ymm3, %%ymm1, %%ymm11\n\t"
                       "vfmadd231pd %%ymm3, %%ymm2, %%ymm15\n\t"
                       "vmovapd %%ymm4, 0(%%rdx)\n\t"
                       "vmovapd %%ymm5, 32(%%rdx)\n\t"
                       "vmovapd %%ymm6, 64(%%rdx)\n\t"
                       "vmovapd %%ymm7, 96(%%rdx)\n\t"
                       "vmovapd %%ymm8, 384(%%rdx)\n\t"
                       "vmovapd %%ymm9, 416(%%rdx)\n\t"
                       "vmovapd %%ymm10, 448(%%rdx)\n\t"
                       "vmovapd %%ymm11, 480(%%rdx)\n\t"
                       "vmovapd %%ymm12, 768(%%rdx)\n\t"
                       "vmovapd %%ymm13, 800(%%rdx)\n\t"
                       "vmovapd %%ymm14, 832(%%rdx)\n\t"
                       "vmovapd %%ymm15, 864(%%rdx)\n\t"
                       "addq $128, %%rdx\n\t"
                       "subq $3328, %%rdi\n\t"
                       "cmpq $48, %%r12\n\t"
                       "jl 1b\n\t"
                       "addq $768, %%rdx\n\t"
                       "addq $216, %%rsi\n\t"
                       "subq $384, %%rdi\n\t"
                       "cmpq $9, %%r13\n\t"
                       "jl 0b\n\t"
                       : : "m"(A), "m"(B), "m"(C) : "rdi","rsi","rdx","r12","r13","r14","xmm0","xmm1","xmm2","xmm3","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15");
}
#else
void gemm_dense_hsw(const double* A, const double* B, double* C) {}
#endif


#ifdef __AVX512F__
void gemm_dense_knl(const double* A, const double* B, double* C) {
  __asm__ __volatile__("movq %0, %%rdi\n\t"
                       "movq %1, %%rsi\n\t"
                       "movq %2, %%rdx\n\t"
                       "movq $0, %%r12\n\t"
                       "movq $0, %%r13\n\t"
                       "movq $0, %%r14\n\t"
                       "0:\n\t"
                       "addq $8, %%r12\n\t"
                       "vmovapd 0(%%rdx), %%zmm23\n\t"
                       "vmovapd 384(%%rdx), %%zmm24\n\t"
                       "vmovapd 768(%%rdx), %%zmm25\n\t"
                       "vmovapd 1152(%%rdx), %%zmm26\n\t"
                       "vmovapd 1536(%%rdx), %%zmm27\n\t"
                       "vmovapd 1920(%%rdx), %%zmm28\n\t"
                       "vmovapd 2304(%%rdx), %%zmm29\n\t"
                       "vmovapd 2688(%%rdx), %%zmm30\n\t"
                       "vmovapd 3072(%%rdx), %%zmm31\n\t"
                       "vmovapd 0(%%rdi), %%zmm0\n\t"
                       "vmovapd 384(%%rdi), %%zmm1\n\t"
                       "vfmadd231pd 0(%%rsi)%{1to8%}, %%zmm0, %%zmm23\n\t"
                       "vfmadd231pd 72(%%rsi)%{1to8%}, %%zmm0, %%zmm24\n\t"
                       "vfmadd231pd 144(%%rsi)%{1to8%}, %%zmm0, %%zmm25\n\t"
                       "vfmadd231pd 216(%%rsi)%{1to8%}, %%zmm0, %%zmm26\n\t"
                       "vfmadd231pd 288(%%rsi)%{1to8%}, %%zmm0, %%zmm27\n\t"
                       "vfmadd231pd 360(%%rsi)%{1to8%}, %%zmm0, %%zmm28\n\t"
                       "vfmadd231pd 432(%%rsi)%{1to8%}, %%zmm0, %%zmm29\n\t"
                       "vfmadd231pd 504(%%rsi)%{1to8%}, %%zmm0, %%zmm30\n\t"
                       "vfmadd231pd 576(%%rsi)%{1to8%}, %%zmm0, %%zmm31\n\t"
                       "vmovapd 768(%%rdi), %%zmm2\n\t"
                       "vmovapd 1152(%%rdi), %%zmm3\n\t"
                       "vfmadd231pd 8(%%rsi)%{1to8%}, %%zmm1, %%zmm23\n\t"
                       "vfmadd231pd 80(%%rsi)%{1to8%}, %%zmm1, %%zmm24\n\t"
                       "vfmadd231pd 152(%%rsi)%{1to8%}, %%zmm1, %%zmm25\n\t"
                       "vfmadd231pd 224(%%rsi)%{1to8%}, %%zmm1, %%zmm26\n\t"
                       "vfmadd231pd 296(%%rsi)%{1to8%}, %%zmm1, %%zmm27\n\t"
                       "vfmadd231pd 368(%%rsi)%{1to8%}, %%zmm1, %%zmm28\n\t"
                       "vfmadd231pd 440(%%rsi)%{1to8%}, %%zmm1, %%zmm29\n\t"
                       "vfmadd231pd 512(%%rsi)%{1to8%}, %%zmm1, %%zmm30\n\t"
                       "vfmadd231pd 584(%%rsi)%{1to8%}, %%zmm1, %%zmm31\n\t"
                       "vmovapd 1536(%%rdi), %%zmm4\n\t"
                       "vmovapd 1920(%%rdi), %%zmm5\n\t"
                       "vfmadd231pd 16(%%rsi)%{1to8%}, %%zmm2, %%zmm23\n\t"
                       "vfmadd231pd 88(%%rsi)%{1to8%}, %%zmm2, %%zmm24\n\t"
                       "vfmadd231pd 160(%%rsi)%{1to8%}, %%zmm2, %%zmm25\n\t"
                       "vfmadd231pd 232(%%rsi)%{1to8%}, %%zmm2, %%zmm26\n\t"
                       "vfmadd231pd 304(%%rsi)%{1to8%}, %%zmm2, %%zmm27\n\t"
                       "vfmadd231pd 376(%%rsi)%{1to8%}, %%zmm2, %%zmm28\n\t"
                       "vfmadd231pd 448(%%rsi)%{1to8%}, %%zmm2, %%zmm29\n\t"
                       "vfmadd231pd 520(%%rsi)%{1to8%}, %%zmm2, %%zmm30\n\t"
                       "vfmadd231pd 592(%%rsi)%{1to8%}, %%zmm2, %%zmm31\n\t"
                       "vmovapd 2304(%%rdi), %%zmm6\n\t"
                       "vmovapd 2688(%%rdi), %%zmm7\n\t"
                       "vfmadd231pd 24(%%rsi)%{1to8%}, %%zmm3, %%zmm23\n\t"
                       "vfmadd231pd 96(%%rsi)%{1to8%}, %%zmm3, %%zmm24\n\t"
                       "vfmadd231pd 168(%%rsi)%{1to8%}, %%zmm3, %%zmm25\n\t"
                       "vfmadd231pd 240(%%rsi)%{1to8%}, %%zmm3, %%zmm26\n\t"
                       "vfmadd231pd 312(%%rsi)%{1to8%}, %%zmm3, %%zmm27\n\t"
                       "vfmadd231pd 384(%%rsi)%{1to8%}, %%zmm3, %%zmm28\n\t"
                       "vfmadd231pd 456(%%rsi)%{1to8%}, %%zmm3, %%zmm29\n\t"
                       "vfmadd231pd 528(%%rsi)%{1to8%}, %%zmm3, %%zmm30\n\t"
                       "vfmadd231pd 600(%%rsi)%{1to8%}, %%zmm3, %%zmm31\n\t"
                       "vmovapd 3072(%%rdi), %%zmm0\n\t"
                       "vfmadd231pd 32(%%rsi)%{1to8%}, %%zmm4, %%zmm23\n\t"
                       "vfmadd231pd 104(%%rsi)%{1to8%}, %%zmm4, %%zmm24\n\t"
                       "vfmadd231pd 176(%%rsi)%{1to8%}, %%zmm4, %%zmm25\n\t"
                       "vfmadd231pd 248(%%rsi)%{1to8%}, %%zmm4, %%zmm26\n\t"
                       "vfmadd231pd 320(%%rsi)%{1to8%}, %%zmm4, %%zmm27\n\t"
                       "vfmadd231pd 392(%%rsi)%{1to8%}, %%zmm4, %%zmm28\n\t"
                       "vfmadd231pd 464(%%rsi)%{1to8%}, %%zmm4, %%zmm29\n\t"
                       "vfmadd231pd 536(%%rsi)%{1to8%}, %%zmm4, %%zmm30\n\t"
                       "vfmadd231pd 608(%%rsi)%{1to8%}, %%zmm4, %%zmm31\n\t"
                       "vfmadd231pd 40(%%rsi)%{1to8%}, %%zmm5, %%zmm23\n\t"
                       "vfmadd231pd 112(%%rsi)%{1to8%}, %%zmm5, %%zmm24\n\t"
                       "vfmadd231pd 184(%%rsi)%{1to8%}, %%zmm5, %%zmm25\n\t"
                       "vfmadd231pd 256(%%rsi)%{1to8%}, %%zmm5, %%zmm26\n\t"
                       "vfmadd231pd 328(%%rsi)%{1to8%}, %%zmm5, %%zmm27\n\t"
                       "vfmadd231pd 400(%%rsi)%{1to8%}, %%zmm5, %%zmm28\n\t"
                       "vfmadd231pd 472(%%rsi)%{1to8%}, %%zmm5, %%zmm29\n\t"
                       "vfmadd231pd 544(%%rsi)%{1to8%}, %%zmm5, %%zmm30\n\t"
                       "vfmadd231pd 616(%%rsi)%{1to8%}, %%zmm5, %%zmm31\n\t"
                       "vfmadd231pd 48(%%rsi)%{1to8%}, %%zmm6, %%zmm23\n\t"
                       "vfmadd231pd 120(%%rsi)%{1to8%}, %%zmm6, %%zmm24\n\t"
                       "vfmadd231pd 192(%%rsi)%{1to8%}, %%zmm6, %%zmm25\n\t"
                       "vfmadd231pd 264(%%rsi)%{1to8%}, %%zmm6, %%zmm26\n\t"
                       "vfmadd231pd 336(%%rsi)%{1to8%}, %%zmm6, %%zmm27\n\t"
                       "vfmadd231pd 408(%%rsi)%{1to8%}, %%zmm6, %%zmm28\n\t"
                       "vfmadd231pd 480(%%rsi)%{1to8%}, %%zmm6, %%zmm29\n\t"
                       "vfmadd231pd 552(%%rsi)%{1to8%}, %%zmm6, %%zmm30\n\t"
                       "vfmadd231pd 624(%%rsi)%{1to8%}, %%zmm6, %%zmm31\n\t"
                       "vfmadd231pd 56(%%rsi)%{1to8%}, %%zmm7, %%zmm23\n\t"
                       "vfmadd231pd 128(%%rsi)%{1to8%}, %%zmm7, %%zmm24\n\t"
                       "vfmadd231pd 200(%%rsi)%{1to8%}, %%zmm7, %%zmm25\n\t"
                       "vfmadd231pd 272(%%rsi)%{1to8%}, %%zmm7, %%zmm26\n\t"
                       "vfmadd231pd 344(%%rsi)%{1to8%}, %%zmm7, %%zmm27\n\t"
                       "vfmadd231pd 416(%%rsi)%{1to8%}, %%zmm7, %%zmm28\n\t"
                       "vfmadd231pd 488(%%rsi)%{1to8%}, %%zmm7, %%zmm29\n\t"
                       "vfmadd231pd 560(%%rsi)%{1to8%}, %%zmm7, %%zmm30\n\t"
                       "vfmadd231pd 632(%%rsi)%{1to8%}, %%zmm7, %%zmm31\n\t"
                       "vfmadd231pd 64(%%rsi)%{1to8%}, %%zmm0, %%zmm23\n\t"
                       "vfmadd231pd 136(%%rsi)%{1to8%}, %%zmm0, %%zmm24\n\t"
                       "vfmadd231pd 208(%%rsi)%{1to8%}, %%zmm0, %%zmm25\n\t"
                       "vfmadd231pd 280(%%rsi)%{1to8%}, %%zmm0, %%zmm26\n\t"
                       "vfmadd231pd 352(%%rsi)%{1to8%}, %%zmm0, %%zmm27\n\t"
                       "vfmadd231pd 424(%%rsi)%{1to8%}, %%zmm0, %%zmm28\n\t"
                       "vfmadd231pd 496(%%rsi)%{1to8%}, %%zmm0, %%zmm29\n\t"
                       "vfmadd231pd 568(%%rsi)%{1to8%}, %%zmm0, %%zmm30\n\t"
                       "vfmadd231pd 640(%%rsi)%{1to8%}, %%zmm0, %%zmm31\n\t"
                       "vmovapd %%zmm23, 0(%%rdx)\n\t"
                       "vmovapd %%zmm24, 384(%%rdx)\n\t"
                       "vmovapd %%zmm25, 768(%%rdx)\n\t"
                       "vmovapd %%zmm26, 1152(%%rdx)\n\t"
                       "vmovapd %%zmm27, 1536(%%rdx)\n\t"
                       "vmovapd %%zmm28, 1920(%%rdx)\n\t"
                       "vmovapd %%zmm29, 2304(%%rdx)\n\t"
                       "vmovapd %%zmm30, 2688(%%rdx)\n\t"
                       "vmovapd %%zmm31, 3072(%%rdx)\n\t"
                       "addq $64, %%rdx\n\t"
                       "addq $64, %%rdi\n\t"
                       "cmpq $48, %%r12\n\t"
                       "jl 0b\n\t"
                       : : "m"(A), "m"(B), "m"(C) : "k1","rax","rbx","rcx","rdx","rdi","rsi","r8","r9","r10","r11","r12","r13","r14","r15","zmm0","zmm1","zmm2","zmm3","zmm4","zmm5","zmm6","zmm7","zmm8","zmm9","zmm10","zmm11","zmm12","zmm13","zmm14","zmm15","zmm16","zmm17","zmm18","zmm19","zmm20","zmm21","zmm22","zmm23","zmm24","zmm25","zmm26","zmm27","zmm28","zmm29","zmm30","zmm31");
};
#else
void gemm_dense_knl(const double* A, const double* B, double* C) {}
#endif
